### PR TITLE
Committing fix for pkg-config dependency

### PR DESCRIPTION
**Pull request by tkralphs**

### CODE REVIEW

**Comment by tkralphs** [comment]
All the build failures here seem to due to time limit or some system problem (network timeout, etc.). I restarted the jobs, but I think this PR is ready to go.

**Comment by tkralphs** [comment]
@dpo The pr is still failing for time limit, but the push build is passing, so we're good to go. By the way, we need to update the Travis build setup. The OS X images available have been changed. I just updated some of the COIN projects for the new images, so I can take a look at this.

**Comment by tkralphs** [comment]
@dpo Can we merge this?

**Comment by dirkschumacher** [comment]
I don't see a problem merging this as it does not make anything worse I suppose. This PR is needed to merge PR #46.

**Comment by tilgovi** [comment]
Bump?

**Comment by tilgovi** [comment]
I had been running `PKG_CONFIG=/usr/local/bin/pkg-config brew install cbc` but this is no longer a viable workaround since Homebrew added environment filtering by default last week. Now it is not possible to install cbc with Homebrew. This PR should fix it.

**Comment by pmangg** [comment]
@tilgovi my current workaround:

```
HOMEBREW_NO_ENV_FILTERING=1 PKG_CONFIG=/usr/local/bin/pkg-config brew install cbc
```

it would be awesome if we 🚢  this PR.

**Comment by dpo** [comment]
Done in #48.

**Pull request closed without merging**
