### PR TITLE
clp: need suite_sparse if build.with? "glpk"

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
The travis/push build is broken. It doesn't do anything and reports success.

**Comment by tkralphs** [comment]
The pr build seems to be fine. This is very strange...

**Comment by dpo** [comment]
I'm thinking it must be a Travis issue because I've never had this happen before.

**Comment by tkralphs** [comment]
Actually, this doesn't seem to work for me, unfortunately. Since we aren't actually building with `--with-glpk`, we didn't really test anything! We probably should test with some of the more problematic options enabled. 

In any case, I finally got this to work by changing `:run` to `:recommeded`. With `:run`, it doesn't actually link to the proper libraries for some reason. I checked the documentation briefly and couldn't see any mention of `:run`, although `:recommended` seems like a strange thing to put there, since it seems as though it would allow disabling `suite-sparse` manually, even while building with `'glpk`, which would break the build. Any ideas?

**Comment by dpo** [comment]
`:run` means that dependency is required at build and run time. `:recommended` isn't the same. The user could disable it with `brew install --with-glpk --without-suitesparse`, which would defeat the purpose.

Did you try to build locally `--with-glpk`?

**Comment by tkralphs** [comment]
Yes, I guessed that `:recommeded` was not correct for the exact reason you pointed out, but `:run` doesn't work. Yes, I tried building locally with `--with-glpk` and it doesn't get the libraries on the link line that it's supposed to. I finally figured out that when I change it to `:recommended`, I see `-lcholmod -lcolad -lamd` and etc., but those are completely missing when it is `:run`. In the end, it reports undefined symbols at link time.

**Pull request merged**
