### PR TITLE
CLP: new formula.

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@tkralphs Should any of the `:optional` dependencies be `:recommended` here?

Is it correct that `mump` should be built `--without-mpi`?

**Comment by tkralphs** [comment]
@dpo This seems to build fine on my machine and all looks good. As for optional versus recommended packages, I don't really know the repercussions of that. For a normal user, what difference will it make when they install? If it's recommended, does it automatically use it if it's present or something? I would say that all of the optional packages are probably almost all recommended in my mind, but something like ASL is either needed or it's not, depending on the use case. For MUMPS, I guess there is a possible performance difference, but I don't know how much. 

As for your question on MUMPS, I don't know. There has been a lot of talk about MUMPS and MPI (as I'm sure you've seen) on the Ipopt mailing list and I guess if we can disable MPI and everything works, that should be the best option.

We have to think carefully about the dependency structure. There's some messiness and possible pitfalls that may require some re-thinking of the build system of COIN itself. I would like to keep dependencies as clean as possible and avoid explicit dependencies that are implied recursively (this is the power of such a dependency structure). 

For example, Glpk cannot be used by Clp unless CoinUtils was also built with Glpk. In fact, I guess that if you build Clp with ```--with-glpk``` when CoinUtils was not also built with that option and then try to use the functionality that depends on Glpk, you will get some kind of error. I'm testing this now.

The way this really should work is that Clp should be able to detect that CoinUtils was built with Glpk and only build with Glpk if CoinUtils was also. So that brings up the question of whether the --with-glpk option can be passed down to CoinUtils if CoinUtils is going to be installed automatically by dependency. I just did a quick test and it appears this doesn't happen by default. I built Clp with ```--with-glpk``` and CoinUtils was not built with that option, so the whole thing is not going to work unless the user installs CoinUtils by hand with that options before installing Clp. But this kind of defeats the purpose.

If CoinUtils is already built and installed with Glpk, then he addition of Glpk to the link line of Clp will already happen automatically through the pkgconfig file, but what I don't think happens at the moment is the definition of the symbol ```COIN_HAS_GLPK```, which is needed. This should be included in ```CoinUtilsConfig.h```, but it's currently not, since we usually expect Glpk to be included as a COIN package, not as an external library.

If you agree, I can export the symbol that's required and test whether not including Glpk as a direct dependency of Clp still allows it to work, as long as CoinUtils is built with Glpk. The only problem will be that users won't be able to see anymore that Glpk is an option for Clp. And they will apparently have to install CoinUtils manually with that option in any case. To make this all work properly, we need to be able to specify options that get passed automatically to dependent projects. Can that be done?

**Comment by tkralphs** [comment]
The build fails if you install Clp with ```--with-glpk``` and CoinUtils has not been previously installed with that option, although I'm not yet clear on why. I thought the build would go through, but there would run-time errors. In any case, this is something we need to address.

**Comment by dpo** [comment]
There are two ways to achieve this:

1. `brew install clp --with-glpk` can pass `--with-glpk` down to `coinutils` when it's built as a dependency. If the user hasn't already installed `coinutils`, that's fine. If `coinutils` has already been installed and the user didn't specify `--with-glpk` at the time, `brew` will abort and tell the user to reinstall `coinutils --with-glpk`.
2. `brew install clp` can detect whether `coinutils` was built `--with-glpk` or not. However, in the event that the user hasn't installed `coinutils` beforehand, `glpk` will never be used as an option.

My preference is option 1.

It's easy to pass options to dependencies. Look at the `--with-openblas` option for instance.

**Comment by tkralphs** [comment]
I guess option 1 is good, at least for now, but will require exposing every low-level option for every dependent package. Seems like a lot of duplication and sort of defeating the purpose of the recursive dependency structure a bit. It would be nice if it worked like autoconf, where the lower-level options are bubbled up automatically and then got passed down automatically without any explicit implementation needed.

**Comment by tkralphs** [comment]
I tried but couldn't easily parse the syntax of how to make this happen myself so maybe you could implement it?

**Comment by dpo** [comment]
It's also occurring to me that if, say, CLP, is built against OpenBLAS, its dependencies should probably also be built against OpenBLAS?

**Comment by dpo** [comment]
ps: regarding optional vs. recommended dependencies, all it changes for the user is they'll have to specify `--with-xxx` or `--without-xxx` depending on what they need. As long as we don't ship bottles, it's not a big difference, but once we have bottles, we'll have to keep in mind that they'll be built with all default options. So the defaults should be the most likely choices.

**Pull request closed without merging**
