### PR TITLE
Update libraries and enable cbc parallel

### PR DESCRIPTION
**Pull request by dirkschumacher**
This PR updates the libraries to the most recent version and also enables parallel support for CBC.
See #44 and #45

### CODE REVIEW

**Comment by dirkschumacher** [comment]
I see the following error. Seems to be related to PR #43 

> Error: coin-or-tools/coinor/osi 0.107.8 did not build
Logs:
     /Users/travis/Library/Logs/Homebrew/osi/00.options.out
     /Users/travis/Library/Logs/Homebrew/osi/01.configure
     /Users/travis/Library/Logs/Homebrew/osi/01.configure.cc
     /Users/travis/Library/Logs/Homebrew/osi/config.log
If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):

**Comment by dirkschumacher** [comment]
Can I help with anything?

**Comment by dirkschumacher** [comment]
@tkralphs friendly ping 👋. I can also offer to co-maintain this repository if that helps.

**Comment by tilgovi** [comment]
I can also help!

**Comment by tkralphs** [comment]
Sorry for the delay! I would be happy to have some help with this. Let me check with my co-maintainer @dpo.

**Comment by dpo** [comment]
All done with updated CI. Will submit another PR to enable CBC parallel. Thank you.

**Pull request closed without merging**
