### PR TITLE
Remove SYMPHONY dependence on DyLP

### PR DESCRIPTION
**Pull request by tkralphs**

### CODE REVIEW

**Comment by tkralphs** [comment]
Hmm, I don't really know what's going on here.

**Comment by tkralphs** [comment]
@dpo In case you are around, do you have any idea on this? I didn't make any substantive change, seems like something changed in the testing on the homebrew side. I did some Googling, but didn't find much. I know the significance and importance of quoting in Shell scripting, but I don't know what is supposed to be quoted exactly.

**Comment by dpo** [comment]
#99 should hopefully resolve the quotes issue. I think it’s a more or less recent Homebrew requirement.

**Comment by dpo** [comment]
@tkralphs Try again after rebasing your branch, now that #99 has been merged.

**Comment by tkralphs** [comment]
OK, looks like we finally got it!

**Pull request merged**
