### PR TITLE
clp: need suite_sparse if build.with? "glpk", part 2

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Let's see if this works for you.

**Comment by tkralphs** [comment]
No joy :(. Building locally had exactly the same result, a link error. I guess you should be seeing the same thing on your machine, right? Can you replicate?

The error on the Travis build is really strange an completely unrelated to what I'm seeing on local builds. What's going on with Travis??

**Comment by dpo** [comment]
The problem is that I have a dozen copies of `amd.h` lying around from various libraries, so it's always able to pick one up.

**Comment by dpo** [comment]
Does CLP depend on CoinUtils even if we're not building `--with-glpk` (and therefore are not depending on OSI)?

**Comment by dpo** [comment]
I guess it does. I'm seeing the same error locally.

**Comment by tkralphs** [comment]
With respect to your [comment](https://github.com/coin-or-tools/homebrew-coinor/pull/36#issuecomment-225327820) on reproducing, the problem is that the link line isn't correct and to reproduce this, it doesn't matter what headers and libraries are already on the machine. At the point of the error, `suite-sparse has already been installed successfully and `amd.h` is picked up, but this doesn't prevent the error. If you cannot reproduce, then this will be a significant clue about what's going on.

**Comment by dpo** [comment]
`brew install clp --with-glpk` certainly works for me. Unfortunately, there's no mention of `amd` in the log files.

**Comment by tkralphs** [comment]
Ah, OK, if it works for you, then there's at least something to investigate, since that means the link line is coming out fine in your case. Can you put up a gist of the build log?

**Comment by dpo** [comment]
There was still a problem with the formula: the path to `suite-sparse` wasn't passed to `configure` if only `--with-glpk` is used. Now it is. Here are my logs: https://gist.github.com/b6e9303a3091dc4f9829d2fb9df91af8

**Comment by tkralphs** [comment]
Yeah, OK, that fixed it!

**Comment by dpo** [comment]
Great!

**Comment by tkralphs** [comment]
By the way, i just noticed that you can do a squash and merge automatically on github. Would you prefer that for these pull requests?

**Comment by dpo** [comment]
I don't have a clear preference. Squash-merge leaves a cleaner history but it's no longer possible to tell what came from a pull request (I think). Does that matter much? I don't know. There are endless discussions on the web about the relative benefits of each and they quickly turn into fanatical religious arguments. If you have a preference, please go for it.

**Comment by tkralphs** [comment]
I don't really have a preference. I was initially against squashing because it does hide the details that went into the development of the pull request in case you want to go back and trace the logic of why things were done a certain way. On the other hand, sometimes there are many little commit that are really irrelevant in the end. I had the impression you liked squashing, but if you don't care, I will probably just do normal merges.

**Pull request merged**
