### PR TITLE
symphony 5.6.16

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Build failure on OSX:
```
/bin/sh ../libtool --tag=CC --mode=compile clang++ -DHAVE_CONFIG_H -I. -I`echo ../include` -I`echo ../include` -I`echo ../Applications/USER/include`  -I/usr/local/Cellar/coinutils/2.10.14/include/coinutils/coin -I/usr/local/Cellar/osi/0.107.9/include/osi/coin -I/usr/local/Cellar/clp/1.16.11/include/clp/coin -I/usr/local/Cellar/cgl/0.59.10/include/cgl/coin -I/usr/local/Cellar/coinutils/2.10.14/include/coinutils/coin -I/usr/local/Cellar/osi/0.107.9/include/osi/coin -I/usr/local/Cellar/clp/1.16.11/include/clp/coin -I/usr/local/Cellar/coinutils/2.10.14/include/coinutils/coin -I/usr/local/Cellar/osi/0.107.9/include/osi/coin  -D__OSI_CLP__      -DHAS_READLINE  -DUSE_CGL_CUTS          -DSIGHANDLER -DHAS_RANDOM -DHAS_SRANDOM -D__NONE__ -D__DARWIN -DCOMPILE_IN_CG -DCOMPILE_IN_CP -DCOMPILE_IN_LP -DCOMPILE_IN_TM   -I/usr/local/opt/readline/include   -DSYMPHONY_BUILD -c -o libSym_la-lp_free.lo `test -f 'LP/lp_free.c' || echo './'`LP/lp_free.c
LP/lp_genfunc.c:2432:28: error: ordered comparison between pointer and zero ('int *' and 'int')
      if(i < 0 && num_cuts > 0) should_stop = TRUE;
                  ~~~~~~~~ ^ ~
1 error generated.
```
All is well on Linux. @tkralphs Any ideas?

**Comment by tkralphs** [comment]
This is fixed [here](https://github.com/coin-or/SYMPHONY/commit/907c0be7372580e849421ffda073af45daed35e5), just need to make a new release.

**Comment by dpo** [comment]
Should I patch in the meantime?

**Comment by tkralphs** [comment]
Sure, if that's easy to do.

**Pull request merged**
