### PR TITLE
Vol: new formula.

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by tkralphs** [comment]
Should we just merge this now anyway, since it's still failing?

**Comment by dpo** [comment]
On Wed, Sep 23, 2015 at 07:08:56PM -0700, Ted Ralphs wrote:
>Should we just merge this now anyway, since it's still failing?

We can merge, but I'm afraid it will keep failing and I'm not understanding
why. The error message is related to the Homebrew test-bot command. But I'm not
getting it locally...

Cheers,

Dominique

**Comment by tkralphs** [comment]
I guess it's up to you. Since Vol is not a dependency for anything and the other recipes seems fine, we could try moving on to the next one without merging this for now and see if we get another failure there.

**Comment by dpo** [comment]
So patience is a virtue, then!

**Pull request merged**
