### PR TITLE
MUMPS 5.5.1

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by tkralphs** [comment]
Hmm, another weird and hard-to-interpret error related to `gfortran`.

**Comment by tkralphs** [comment]
Should we install/update `gfortran`? If so, should this be done with `apt` or `brew`?

**Comment by dpo** [comment]
The formula already installs gfortran. The error only occurs on Linux. The macOS build succeeds. I asked the Homebrew folks what to make of the Linux error.

**Comment by tkralphs** [comment]
> The formula already installs gfortran

Oh yes, that makes sense.

**Pull request closed without merging**
