### PR TITLE
CoinUtils: new formula.

### PR DESCRIPTION
**Pull request by dpo**
Specify include dir to avoid clashes with other COIN formulae.

### CODE REVIEW

**Comment by dpo** [comment]
Build will fail until #2 is merged.

**Comment by tkralphs** [comment]
The build is failing, even after merging #2 (see log [here](https://travis-ci.org/coin-or-tools/homebrew-coinor/builds/72326916)). I tried this on my local machine and got the same result. Seems to be because you are specifying a path in ```\usr\local\opt``` instead of ```\usr\local``` for the data file. 

Incidentally, ```brew install``` was initially failing for me locally until I updated to the latest homebrew version. I guess this is not a big problem, since I assume that the recipes in the official repo are matched with compatible versions automatically?

**Comment by tkralphs** [comment]
Well, I tried to fix this, but with my limited knowledge of Homebrew, I failed. I couldn't seem to get it to produce the right directory after trying a number of things. Of course, I should RTFM, but I think you can fix it more quickly @dpo :).

**Comment by dpo** [comment]
It seems to build now. Somehow the updates from #2 were not reflected here. The only remaining error is that `coinutils` is also present in Homebrew/Science. If this formula looks good to you, I'll remove it from there.

It would be best to have a test for each package in the form of a short program that we could compile, link against the libraries, and run. See for example the formula for `armadillo` in Homebrew/Science for an example of what I mean.

**Comment by tkralphs** [comment]
This looks OK now.

**Pull request merged**
