### PR TITLE
Vol: new formula.

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
I'm getting a bunch of warnings and errors in the tests, but not sure if we should be worried: https://gist.github.com/88f52277109022efb70c

**Comment by dpo** [comment]
Also, `configure --help` says that `coinutils` and `osi` are optional. Should we mark `osi` as `:recommended`? In that case, we should also add `depends_on "coinutils" => :recommended`.

**Comment by tkralphs** [comment]
Look good and builds fine for me.

I would make ```osi``` recommended. Since ```osi``` requires ```coinutils```, it should just get picked up automatically if osi gets installed, though, right? Seems like we would be trying to do the job of the dependency mechanism by specifying it explicitly. For example, what if the library that Osi depends on changed names or we eliminated the dependency altogether? This wold be a problem if we were not the ones in control of osi. Or what if we didn't actually know the full dependency structure? As we go up the hierarchy, the dependency recursion will get up to 4 levels deep and we don't want to have to list all the dependencies all the way down just to make something recommended, right? This will be a big issue when we get to ```OS```, which has virtually every other solver as an optional extension and most (if not all) will be recommended.

As an aside, ```configure --help``` isn't a reliable way to determine which packages are optional. Any package that has an argument ```--with-pkg``` argument is taken to be optional by autoconf and I suppose that is what the existence of such an argument would normally indicate. I'm not sure if are abusing the use of such an arguments a bit by using them for required packages---I never really noticed that before and perhaps there is a different way to specify the location of a required package. 

We use those arguments to get the path to packages that have been installed in a non-standard location, even if they are required. The argument itself is optional, since any required library installed in a standard location or for which we have a .pc will just get picked up (hence the fact that we don't need to use those arguments for the required packages).

The errors are normal and nothing to worry about. We implemented a mechanism of being able to designate certain errors as "expected" to take care of the face that that some of the OSI interfaces either don't support certain functionality that's typically expected or do things in a slightly non-standard way. The worrisome are errors are the ones that are unexpected. Perhaps that's more confusing than it should be.

**Comment by dpo** [comment]
Yes, `osi` requires `coinutils`, but if `osi` is `:recommended`, a user could build `--without-osi`, and in that case, they don't have the option of building against `coinutils`. So `coinutils` should also be `:recommended`.

**Comment by tkralphs** [comment]
OK, right, that make sense, but I guess what I didn't say explicitly is that ```coinutils``` is only needed as a depedency of ```osi``` and that's the case my comments were referring to. As far as I can tell, ```vol``` doesn't directly use ```coinutils``` for any functionality, so I guess it should not be listed as optional or recommended, right? I now see that this is another confusing side effect of the --with-coinutils argument to configure. It doesn't make this situation clear.

**Comment by dpo** [comment]
Thanks, I understand the issue. One of the challenges I have is figuring out the dependencies of a given package (optional or not). Often, the `README` and `INSTALL` files are essentially empty.

**Comment by dpo** [comment]
Please don't merge this. Something's wrong with Travis and I'm not sure what.

**Comment by tkralphs** [comment]
This probably has nothing to do with the problem on Travis, but I had to manually run a command as root in order to agree to the new XCode license before I could ```brew install``` just now. Full output below.
```
brew install --verbose --debug vol
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/coin-or-tools/homebrew-coinor/vol.rb

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool
/usr/local/Library/Homebrew/mach.rb:170:in `parse_otool_L_output'
/usr/local/Library/Homebrew/mach.rb:163:in `initialize'
/usr/local/Library/Homebrew/mach.rb:187:in `new'
/usr/local/Library/Homebrew/mach.rb:187:in `mach_metadata'
/usr/local/Library/Homebrew/mach.rb:197:in `dynamically_linked_libraries'
/usr/local/Library/Homebrew/cmd/doctor.rb:383:in `check_for_bad_install_name_tool'
/usr/local/Library/Homebrew/cmd/install.rb:144:in `block in check_xcode'
/usr/local/Library/Homebrew/cmd/install.rb:143:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:143:in `check_xcode'
/usr/local/Library/Homebrew/cmd/install.rb:169:in `perform_preinstall_checks'
/usr/local/Library/Homebrew/cmd/install.rb:92:in `install'
/usr/local/Library/brew.rb:133:in `<main>'
```

**Comment by tkralphs** [comment]
Everything went perfectly for me with the new formula, so I'm not sure what's happening on Travis. I can certainly help with determining what packages are required/recommended/optional. I think the easiest and most reliable way is just to look in the ```configure.ac``` for a line like
```
  AC_MSG_ERROR([One or more required packages CoinUtils, Osi, and Cgl are not available.])
```
I think this should tell you for each project what is really required for the package to build. There is a chance that some of the error messages will be less helpful than this one and this also isn't 100% reliable (for example, this is ```cbc```, which technically doesn't require ```clp``` if there is another LP solver available, but I think we want to consider ```clp``` to be required in this context), but it's a good enough starting point and then we can iterate. I can also try to make a list somewhere if you think that's better. 

There's also slide 28 [here](http://coral.ie.lehigh.edu/~ted/files/coin-or/slides/COINIntro.pdf), which shows the dependencies graphically and I think should have most of the hard and fast requirements.

**Comment by dpo** [comment]
Thanks! I've no idea why the Travis build errors out here. It's complaining about something inside Homebrew itself, but the problem doesn't occur for me, nor does it for you! I'll close this PR and open a fresh one just in case.

**Pull request closed without merging**
