### PR TITLE
coin_data_netlib: update url and sha

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Success! @tkralphs

**Comment by tkralphs** [comment]
Horray :)?! I'm still confused as to what's been going on. On Travis, this pull request is associated with multiple different SHAs, but here, nothing seems to have changed. What happened? I still think we should pull from `pkgsource/` for consistency, even though `source/` is identical in this case.

**Comment by dpo** [comment]
Done.

**Comment by tkralphs** [comment]
I'm getting the same error locally that is reported [here](https://travis-ci.org/coin-or-tools/homebrew-coinor/jobs/135715343). The SHA doesn't in fact seem to be right. The push build didn't Work (seems like the same problem we were having before--it didn't actually build). If I fix the SHA, then everything build locally.

**Comment by dpo** [comment]
I wonder what's wrong. I submitted a PR to fix the sha sum.

**Pull request merged**
