### PR TITLE
New package versions

### PR DESCRIPTION
**Pull request by Alexander-Belyi**
As discussed in #70, I've updated `coin_data_*.rb` files with new links pointing to the `coin-or-tools/Data-*`. I am also updating the `Clp` version.

### CODE REVIEW

**Comment by dpo** [comment]
I suggest we wait for #68

**Comment by dpo** [comment]
Could you please rebase this PR? Thanks!

**Comment by tkralphs** [comment]
Closing and re-opening should rebase it, right?

**Comment by dpo** [comment]
No, only git can rebase. It has to be done manually.

**Comment by Alexander-Belyi** [comment]
Was it enough to merge master in here, or do I need to do something else?
I'm not sure, why checks fail. This `revision 1` was there and supposedly passed previously.

**Comment by dpo** [comment]
Your branch is still in conflict. A rebase differs from a merge. Ideally, your merge commits shouldn't be there at all. The procedure is something like this:
```
git checkout master
git pull
git checkout your-branch
git rebase master
# fix conflicts and commit
git push -f
```

**Comment by tkralphs** [comment]
OK, yeah, sorry, it doesn't rebase, but when there are no conflicts, it creates a merge commit for testing that is the same as you would get if you rebased, right? It incorporates newer commits before re-running the tests. If tests pass, then you can just rebase when you merge. I didn't think there were conflicts, where there? Maybe I missed that. 

In any case, it looks like the failures are because there shouldn't be a `revision 1` in 5 of the files. Maybe you can now do an interactive rebase to get rid of the merge commits, and then remove the `revision 1`s.  Sound right, @dpo ?

**Comment by dpo** [comment]
Yes, there were conflicts. GitHub indicates that there are conflicts below the CI checks (scroll all the way down this page) and you'll see
Screen Shot 2022-03-04 at 15 13 34

Right, the `revision n` line should be removed when we update the version of a formula. When we update the formula itself (e.g., to add a build option or fix something) but keep the version the same, we increment the revision number by 1.

**Comment by tkralphs** [comment]
OK, I've seen the conflict warning before and I understand what it means, I just missed it in this case.

**Comment by Alexander-Belyi** [comment]
Why don't I see that there are conflicts?
image

> Maybe you can now do an interactive rebase to get rid of the merge commits, and then remove the `revision 1`s.

Ok, thanks, I'll do it!

**Comment by tkralphs** [comment]
The conflicts were there previously, but the merge commits did eliminate them. It's just that we don't want the merge commits in the PR and when you remove them, you'll have conflicts again. Then you rebase. At least that's what I think :).

**Comment by dpo** [comment]
For me, GitHub says there are still conflicts after the merge commits. I'm a bit puzzled as to why yours appears different.

**Comment by tkralphs** [comment]
> For me, GitHub says there are still conflicts after the merge commits. I'm a bit puzzled as to why yours appears different.

The difference is probably that for me, "Squash and Merge" is coming up as the default and when squashing, there is no conflict. If I switch to "rebase and merge", then I get a conflict. This also explains why I didn't see any conflict previously either. I'm not exactly sure how it determines which users see which defaults, but apparently, it's customized per user. I assume it's somehow based on what you did the last time.

**Comment by Alexander-Belyi** [comment]
@dpo, @tkralphs, thank you for your explanations! I've learned something new about git and github.

**Comment by dpo** [comment]
Amazing job @Alexander-Belyi ! Many thanks!

**Comment by tkralphs** [comment]
> @dpo, @tkralphs, thank you for your explanations! I've learned something new about git and github.

I think I only managed to confuse matters, but no problem! And thank you @Alexander-Belyi for taking the time and effort to do this!

**Pull request closed without merging**
